### ISSUE TITLE
Define a permissive licence, like MIT or BSD

### ISSUE THREAD

**Issue by luzfcb** [adlh/django-multinavigation#1]
http://www.tldrlegal.com/license/mit-license
http://www.tldrlegal.com/license/bsd-3-clause-license-(revised)

**Comment by xizhao** [comment]
Yes, you must license this otherwise people can't legally use it!
Reverse search (yellow button to the right of searchbar on top) on tldrlegal might help you find one.

**Comment by adlh** [comment]
Sorry, I actually wanted to add this as a package and everything suggested by luzfcb and even started a (very brief) attemt some months ago. I'll try to do that at some point on the future, but yes, I will add a license at least.

**Comment by luzfcb** [comment]
@adlh 

If you are interested in creating a package, you can do this easily using a project template for creating packages

https://github.com/pydanny/cookiecutter-djangopackage
https://github.com/audreyr/cookiecutter-pypackage

Both use "cookiecutter" to create the template

https://github.com/audreyr/cookiecutter
